config/routes.rb
FoldIdea::Application.routes.draw do
  devise_for :users
  get 'profile/:id', to: 'home#profile', as: :profile
  resources :base_units do
    resources :trays, shallow: true
  end

  root 'home#index'

end

app/models/tray.rb
class Tray < ActiveRecord::Base
  belongs_to :base_unit

  VALID_GAP_PERCENTS = [ 0.02, 0.03, 0.05, 0.07 ]

  validates :files, presence: true, numericality: { greater_than: 0 }
  validates :ranks, presence: true, numericality: { greater_than: 0 }
  validates :gap_percent, presence: true, inclusion: { in: VALID_GAP_PERCENTS }

  def to_param
    "#{id}-#{"#{base_unit.name}-#{files}x#{ranks}".parameterize('-')}"
  end

  def file_size
    gap_width = (base_unit.base_width.to_f * gap_percent)
    (files * (base_unit.base_width.to_f + gap_width) + gap_width ).round
  end

  def rank_size
    gap_length = (base_unit.base_length.to_f * gap_percent)
    (ranks * (base_unit.base_length.to_f + gap_length) ).round
  end
end

app/controllers/trays_controller.rb
class TraysController < ApplicationController
  # GET /trays/1
  # GET /trays/1.json
  def show
    @tray = Tray.find params[:id]

    respond_to do |format|
      format.html
      format.pdf
    end
  end

  # POST /trays
  # POST /trays.json
  def create
    @base_unit = BaseUnit.find params[:base_unit_id]
    @tray = @base_unit.trays.create(tray_params)
    redirect_to @base_unit, notice: 'Tray was successfully added.'
  end

  # GET /trays/1/edit
  def edit
    @tray = Tray.find params[:id]
  end

  # PATCH/PUT /trays/1
  # PATCH/PUT /trays/1.json
  def update
    @tray = Tray.find params[:id]

    respond_to do |format|
      if @tray.update(tray_params)
        format.html { redirect_to @tray.base_unit, notice: 'Tray was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  # DELETE /trays/1
  # DELETE /trays/1.json
  def destroy
    @tray = Tray.find params[:id]
    @base_unit = @tray.base_unit
    @tray.destroy
    respond_to do |format|
      format.html { redirect_to @base_unit, notice: 'Tray was destroyed.' }
      format.json { head :no_content }
    end
  end

private
  # Never trust parameters from the scary internet, only allow the white list through.
  def tray_params
    params.require(:tray).permit(:files, :ranks, :gap_percent)
  end
end

app/helpers/trays_helper.rb
require 'prawn/measurement_extensions'
require 'open-uri'

module TraysHelper
  def tray_gap(val)
    gap = val.kind_of?(Tray) ? val.gap_percent : val.to_f
    (gap * 100).round
  end

  def render_tray_pdf(pdf, tray, start_y, start_x = 0)
    tray_width = tray.file_size.mm
    tray_height = tray.rank_size.mm
    start_y = start_y - (40.mm + tray_height)
    # todo - get a background image, but for now, just use dummy
    bg_image = { file: 'app/assets/images/grass_background_yellow.jpg', width:35.mm, height:35.mm }
    tray_background pdf, start_x, start_y, tray_width, tray_height, bg_image
    tray_tabs_with_braces pdf, :bottom, start_x, start_y, tray_width
    tray_tabs_with_braces pdf, :top, start_x, start_y + 20.mm + tray_height, tray_width
    tray_tabs_with_braces pdf, :left, start_x, start_y + 20.mm, tray_height
    tray_tabs_with_braces pdf, :right, start_x + 20.mm + tray_width, start_y + 20.mm, tray_height
  end

  def tray_tabs_with_braces(pdf, position, start_x, start_y, dimension)
    tray_tabs pdf, position, start_x, start_y, dimension
    if [ :top, :bottom ].include?(position)
      brace_top_style = position == :bottom ? :valley : :cut
      brace_bottom_style = position == :top ? :valley : :cut
      fc = pdf.fill_color
      pdf.fill_color('FFFFFF')
      pdf.fill { pdf.rectangle [ start_x + 15.mm, start_y + 20.mm ], 5.mm, 20.mm }
      fold_rectangle pdf, [ start_x + 15.mm, start_y ], 5.mm, 20.mm, top: brace_top_style, bottom: brace_bottom_style, right: :skip
      pdf.fill { pdf.rectangle [ start_x + 20.mm + dimension, start_y + 20.mm ], 5.mm, 20.mm }
      fold_rectangle pdf, [ start_x + 20.mm + dimension, start_y ], 5.mm, 20.mm, top: brace_top_style, bottom: brace_bottom_style, left: :skip
      pdf.fill_color(fc)
    else
      offset_sx = position == :right ? 5.mm : 0
      offset_ex = position == :left ? 15.mm : 20.mm
      fold_line pdf, [ start_x + offset_sx, start_y ], [ start_x + offset_ex, start_y ]
      fold_line pdf, [ start_x + offset_sx, start_y + dimension ], [ start_x + offset_ex, start_y + dimension ]
    end
  end

  def tray_tabs(pdf, position, start_x, start_y, dimension)
    styles = {}
    fold_offsets = [ 10, 5 ]
    width = dimension
    height = 20.mm
    case position
      when :top
        start_x += 20.mm
        styles[:bottom] = :valley
        fold_offsets = [ 5, 5 ]
      when :bottom
        start_x += 20.mm
        styles[:top] = :valley
      when :left
        styles[:right] = :valley
        styles[:top] = styles[:bottom] = :skip
        width = 20.mm
        height = dimension
      when :right
        styles[:left] = :valley
        styles[:top] = styles[:bottom] = :skip
        width = 20.mm
        height = dimension
        fold_offsets = [ 5, 5 ]
    end
    fold_rectangle pdf, [ start_x, start_y ], width, height, styles
    offset_mm = 0
    fold_offsets.each_with_index do |offset,idx|
      offset_mm += offset.mm
      offset_sx, offset_sy, offset_ex, offset_ey = case position
        when :top, :bottom then [ 0, offset_mm, width, offset_mm ]
        when :left, :right then [ offset_mm, 0, offset_mm, height ]
      end
      fold_line pdf, [ start_x+offset_sx, start_y+offset_sy ], [ start_x+offset_ex, start_y+offset_ey ], :mountain
    end
  end

  def fold_line(pdf, corner1, corner2, style = :cut)
    case (style || :cut)
      when :valley
        pdf.dash(3.5, space: 2)
      when :mountain
        pdf.dash(1.5, space: 1.2)
      else
        pdf.undash
    end
    pdf.line corner1, corner2
    pdf.stroke
    pdf.undash
  end

  def fold_rectangle(pdf, corner, width, height, styles = {})
    x = corner[0]
    y = corner[1]
    lw = pdf.line_width
    pdf.line_width(1)
    [ :left, :top, :right, :bottom ].each do |edge|
      next if styles[edge] == :skip
      case edge
        when :left then fold_line pdf, [x, y], [x, y+height], styles[edge]
        when :top then fold_line pdf, [x, y+height], [x+width, y+height], styles[edge]
        when :right then fold_line pdf, [x+width, y+height], [x+width, y], styles[edge]
        when :bottom then fold_line pdf, [x+width, y], [x, y], styles[edge]
      end
    end
    pdf.line_width = lw
  end

  def tray_background(pdf, start_x, start_y, tray_width, tray_height, bg_image)
    sx = start_x + 10.mm
    sy = start_y + 10.mm
    img = bg_image[:file] || open(bg_image[:source])
    tex = sx + tray_width + 20.mm
    tey = sy + tray_height + 20.mm
    over_x = nil
    over_y = nil
    while sy < tey
      while sx < tex
        pdf.image img, width: bg_image[:width], height: bg_image[:height], :at => [ sx, sy + bg_image[:height] ]
        sx += bg_image[:width]
      end
      over_x = over_x || (sx - tex)
      sx = start_x + 10.mm
      sy += bg_image[:height]
    end
    over_y = sy - tey
    fc = pdf.fill_color
    lc = pdf.stroke_color
    pdf.fill_color('ffffff')
    pdf.stroke_color('ffffff')
    if over_y > 0
      pdf.fill_and_stroke { pdf.rectangle [ start_x + 10.mm, start_y + 30.mm + tray_height + over_y ], tray_width + 20.mm + over_x, over_y }
    end
    if over_x > 0
      pdf.fill_and_stroke { pdf.rectangle [ start_x + 30.mm + tray_width, start_y + 30.mm + tray_height ], over_x, tray_height + 20.mm }
    end
    pdf.fill_and_stroke { pdf.rectangle [ start_x + 10.mm, start_y + 20.mm ], 5.mm, 10.mm }
    pdf.fill_and_stroke { pdf.rectangle [ start_x + 10.mm, start_y + 30.mm + tray_height ], 5.mm, 10.mm }
    pdf.fill_and_stroke { pdf.rectangle [ start_x + 25.mm + tray_width, start_y + 20.mm ], 5.mm, 10.mm }
    pdf.fill_and_stroke { pdf.rectangle [ start_x + 25.mm + tray_width, start_y + 30.mm + tray_height ], 5.mm, 10.mm }
    pdf.stroke_color(lc)
    pdf.fill_color(fc)
  end
end

app/views/trays/_form.html.erb
<%= form_for([@base_unit, @base_unit.trays.build]) do |f| %>
<table>
  <tbody>
    <tr>
      <td>
        <%= f.number_field :files, min: 1, class: 'short' %>
        x
        <%= f.number_field :ranks, min: 1, class: 'short' %>
      </td>
      <td>
        <%- Tray::VALID_GAP_PERCENTS.each do |pct| -%>
          <%= f.radio_button :gap_percent, pct %><%= f.label :gap_percent, "#{tray_gap(pct)}%", value: pct %><br/>
        <%- end -%>
      </td>
      <td>
        <%= f.submit 'Add' %>
      </td>
    </tr>
  </tbody>
 </table>
<% end %>

app/views/trays/_tray.html.erb
<tr>
  <td><%= tray.files %>x<%= tray.ranks %></td>
  <td><%= tray_gap(tray) %>% gap</td>
  <td>
    <%= link_to 'Display', tray %>
    <div class="admin">
      <%= link_to 'Edit', edit_tray_path(tray) %> |
      <%= link_to 'Destroy', tray, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  </td>
</tr>

app/views/trays/_tray_display.html.erb
<div class="tray">
  <style type="text/css" scoped>
	  .tr_file { width: <%= tray.file_size %>mm; }
	  .tr_rank { height: <%= tray.rank_size %>mm; }
  </style>
	<div class="tr_bg tr_rank tr_file">
		<%= image_tag 'grass_background_yellow.jpg' %>
	</div>
  <div class="tr_ftab w_top clearfix">
    <div class="tr_cnr"></div>
    <div class="tr_flap"></div>
    <div class="tr_fedge tr_file">
      <div class="tr_fulap"></div>
      <div class="tr_frim"></div>
      <div class="tr_frim"></div>
    </div>
    <div class="tr_flap"></div>
    <div class="tr_cnr"></div>
  </div>
  <div class="tr_rmid tr_rank clearfix">
    <div class="tr_rulap"></div>
    <div class="tr_rrim w_lfo"></div>
    <div class="tr_rrim w_lf"></div>
    <div class="tr_file"></div>
    <div class="tr_rrim w_rt"></div>
    <div class="tr_rrim w_rto"></div>
    <div class="tr_rulap"></div>
  </div>
  <div class="tr_ftab w_bot clearfix">
    <div class="tr_cnr"></div>
    <div class="tr_flap"></div>
    <div class="tr_fedge tr_file">
      <div class="tr_frim"></div>
      <div class="tr_frim"></div>
      <div class="tr_fulap"><%= tray.base_unit.name %> <%= tray.files %>x<%= tray.ranks %></div>
    </div>
    <div class="tr_flap"></div>
    <div class="tr_cnr"></div>
  </div>
</div>

app/views/trays/edit.html.erb
<% title "Edit #{@tray.base_unit.name} Tray" %>
<% body_style 'narrow' %>
<h1>Editing <%= @tray.base_unit.name %> Tray</h1>

<%= form_for @tray do |f| %>
	<p>
		<%= f.label :files %><br/>
		<%= f.number_field :files, min: 1 %>
	</p>

	<p>
		<%= f.label :ranks %><br/>
		<%= f.number_field :ranks, min: 1 %>
	</p>

	<p>
		<%= f.label :gap_percent %><br/>
	  <%- Tray::VALID_GAP_PERCENTS.each do |pct| -%>
	    <%= f.radio_button :gap_percent, pct %><%= f.label :gap_percent, "#{tray_gap(pct)}%", value: pct %><br/>
	  <%- end -%>
	</p>

	<p>
		<%= f.submit 'Save' %>
	</p>
<% end %>

<p class="actions">
  <%= link_to 'Back', @tray.base_unit %>
</p>

app/views/trays/show.html.erb
<% title "#{@tray.base_unit.name} #{@tray.files}x#{@tray.ranks} Tray" %>
<%= render 'tray_display', tray:@tray %>

<p class="actions">
  <%= link_to 'Print', tray_path(format: :pdf), target: '_blank' %> |
  <%= link_to 'Back', @tray.base_unit %>
</p>