config/routes.rb
FoldIdea::Application.routes.draw do
  devise_for :users
  get 'profile/:id', to: 'home#profile', as: :profile
  resources :base_units do
    resources :trays, shallow: true
  end

  root 'home#index'

end

app/views/layouts/application.html.erb
<% session.delete :justloggedin %>
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) || '' %> - FoldIt.co</title>
  <meta name='viewport' content='width=device-width, initial-scale=1.0' />
  <link href='http://fonts.googleapis.com/css?family=Nova+Square' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= yield :styles %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= yield :body_style %>">
<div id="hdr">
  <div class="hdr_lt"></div>
  <div class="hdr_fold smcaps" onclick="location='/';">FOLD</div>
  <div class="hdr_main">
    <span class="hdr_logo_rt smcaps" onclick="location='/';">IT<em>.co</em></span>
    <!--<div id="zone" class="<%= yield(:zone_class).presence || "z_#{controller_name}" %>">-->
      <!--<%=h yield(:zone_name).presence || controller_name.titleize %>-->
    <!--</div>-->
      <div id='acct' class="<%= user_signed_in? ? 'w_login' : 'w_logout' %>">
        <ul class="tpop">
          <%- if user_signed_in? -%>
              <li><%= link_to current_user.display_handle, profile_path(:id => current_user.to_param) %></li>
              <li><%= link_to 'Manage Account', edit_user_registration_path %></li>
              <li><%= link_to 'Log Out', destroy_user_session_url, method:'delete' %></li>
          <%- else -%>
              <li><%= link_to 'Log In', new_user_session_url %></li>
              <li><%= link_to 'Create Account', new_user_registration_path %></li>
          <%- end -%>
        </ul>
      </div>
  </div>
  <div class="hdr_rt"></div>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</div>
<div id="content">
  <div class="lyo_cnt">
    <%= yield %>
  </div>
</div>
<div id="ftr_gap"></div>
<div id="ftr">
  <div class="lyo_cnt">
    Copyright &copy 2014 <%= site_name %>
  </div>
</div>

</body>
</html>