config/routes.rb
FoldIdea::Application.routes.draw do
  devise_for :users
  get 'profile/:id', to: 'home#profile', as: :profile
  resources :base_units do
    resources :trays, shallow: true
  end

  root 'home#index'

end

app/models/base_unit.rb
class BaseUnit < ActiveRecord::Base
  has_many :trays, dependent: :destroy

  validates :name, presence: true, length: { minimum: 5, maximum: 100 }
  validates :base_length, presence: true, numericality: { greater_than: 0 }
  validates :base_width, presence: true, numericality: { greater_than: 0 }

  def to_param
    "#{id}-#{name.parameterize('-')}"
  end
end

app/controllers/base_units_controller.rb
class BaseUnitsController < ApplicationController
  before_action :set_base_unit, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]

  # GET /base_units
  # GET /base_units.json
  def index
    @base_units = BaseUnit.all
  end

  # GET /base_units/1
  # GET /base_units/1.json
  def show
  end

  # GET /base_units/new
  def new
    @base_unit = BaseUnit.new
  end

  # GET /base_units/1/edit
  def edit
  end

  # POST /base_units
  # POST /base_units.json
  def create
    @base_unit = BaseUnit.new(base_unit_params)

    respond_to do |format|
      if @base_unit.save
        format.html { redirect_to @base_unit, notice: 'Tray type was successfully created.' }
        format.json { render action: 'show', status: :created, location: @base_unit }
      else
        format.html { render action: 'new' }
        format.json { render json: @base_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /base_units/1
  # PATCH/PUT /base_units/1.json
  def update
    respond_to do |format|
      if @base_unit.update(base_unit_params)
        format.html { redirect_to @base_unit, notice: 'Tray type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @base_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /base_units/1
  # DELETE /base_units/1.json
  def destroy
    @base_unit.destroy
    respond_to do |format|
      format.html { redirect_to base_units_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_base_unit
      @base_unit = BaseUnit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def base_unit_params
      params.require(:base_unit).permit(:name, :base_width, :base_length)
    end
end

app/helpers/base_units_helper.rb
module BaseUnitsHelper
end

app/views/base_units/_form.html.erb
<%= form_for(@base_unit) do |f| %>
  <% if @base_unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@base_unit.errors.count, "error") %> prohibited this base_unit from being saved:</h2>

      <ul>
      <% @base_unit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="measure_grid">
		<div class="mg_axes">Measure Base Here</div>
		<ul class="mg_ylabels">
            <%- top = 0 -%>
			<%- 60.step(0, -10).each do |lbl| -%>
				<li style="top: <%= top %>mm;"><%= lbl %></li>
                <%- top += 10 -%>
			<%- end -%>
		</ul>
		<ul class="mg_yaxis">
            <%- top = 0 -%>
			<%- 60.downto(0).each do |idx| -%>
				<li class="<%= (idx % 10 == 0) ? 'ten' : ( (idx % 5 == 0 ? 'five' : 'one') ) %>" style="top: <%= top %>mm;">&nbsp;</li>
                <%- top += 1 -%>
			<%- end -%>
		</ul>
		<ul class="mg_xaxis">
			<%- 0.upto(60).each do |idx| -%>
				<li class="<%= (idx % 10 == 0) ? 'ten' : ( (idx % 5 == 0 ? 'five' : 'one') )%>" style="left: <%= idx %>mm;">&nbsp;</li>
			<%- end -%>
		</ul>
		<ul class="mg_xlabels">
			<%- 0.step(60, 10).each do |lbl| -%>
				<li style="left: <%= lbl %>mm;"><%= lbl %></li>
			<%- end -%>
		</ul>
	</div>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :base_width %><br>
    <%= f.number_field :base_width, min: 1 %> mm
  </div>
  <div class="field">
    <%= f.label :base_length %><br>
    <%= f.number_field :base_length, min: 1 %> mm
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/base_units/edit.html.erb
<% title 'Edit Tray Type' %>
<% zone 'Trays' %>
<% body_style 'narrow' %>
<h1>Editing Tray Type</h1>

<%= render 'form' %>

<p class="actions">
	<%= link_to 'Show', @base_unit %> |
	<%= link_to 'Back', base_units_path %>
</p>

app/views/base_units/index.html.erb
<% title 'Tray Types' %>
<% zone 'Trays' %>
<% body_style 'narrow' %>
<h1>Tray Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Base Size</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <%- @base_units.each do |base_unit| -%>
      <tr>
        <td><%= base_unit.name %></td>
        <td><%= base_unit.base_width %>x<%= base_unit.base_length %>mm</td>
        <td>
          <%= link_to 'Trays', base_unit %>
          <div class="admin">
            <%= link_to 'Edit', edit_base_unit_path(base_unit) %> |
            <%= link_to 'Destroy', base_unit, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        </td>
      </tr>
    <%- end -%>
  </tbody>
</table>

<p class="actions"><%= link_to 'Add Tray Type', new_base_unit_path %></p>

app/views/base_units/new.html.erb
<% title 'New Tray Type' %>
<% zone 'Trays' %>
<% body_style 'narrow' %>
<h1>New Tray Type</h1>

<%= render 'form' %>

<p class="actions">
	<%= link_to 'Back', base_units_path %>
</p>

app/views/base_units/show.html.erb
<% title "#{@base_unit.name} Trays" %>
<% zone 'Trays' %>
<% body_style 'narrow base_unit_show' %>
<h1><%= @base_unit.name %> Trays</h1>

<p id="notice"><%= notice %></p>

<p class="data">
  <strong>Base Size:</strong>
  <%= @base_unit.base_width %>x<%= @base_unit.base_length %>mm
</p>

<table>
  <thead>
    <tr>
      <th>Files x Ranks</th>
      <th>Spacing</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <%= render @base_unit.trays %>
  </tbody>
</table>
<%= render 'trays/form' %>

<p class="actions">
    <%= link_to 'Edit', edit_base_unit_path(@base_unit) %> |
    <%= link_to 'Back', base_units_path %>
</p>